# Contributor
type contributor {
  avatar: String,
  discriminator: String,
  guild_id: String,
  id: String,
  message_count: Float,
  monetize_xp_boost: Float,
  username: String,
  xp: Float,
  is_monetize_subscriber: Boolean,
  detailed_xp: [Float],
  level: Float
  avatarUrl: String
}


# Telegram News
type telegramNews {
  title: String,
  description: String,
  url: String,
  urlToImage: String,
  publishedAt: String,
  content: String
}

# Query
type Query {
  topContributors: [contributor]
  recentNews: [telegramNews]
}

# Mutation
type Mutation {
  voteProject(id: ID): Project
}