name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_HOST }}
          username: ${{ secrets.MAIN_USERNAME }}
          key: ${{ secrets.MAIN_KEY }}
          script: |
            source ~/.profile 
            cd ~/stack/projects/monluminati-cms
            git pull
            yarn install
            yarn build
            pm2 restart 0